#!/usr/bin/env bash
set -e
make docs
# Check that documentation was not changed
if ! git diff --exit-code
then
    echo "==============================================="
    echo "Documentation files are changed."
    echo "Add them to the staging area before proceeding."
    exit 1
fi
make test
